/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["api_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["api_auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_budgets_list"];
        put?: never;
        post: operations["api_budgets_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets/{budget_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_budgets_retrieve"];
        put?: never;
        post?: never;
        delete: operations["api_budgets_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_budgets_partial_update"];
        trace?: never;
    };
    "/api/budgets/{budget_id}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_budgets_categories_list"];
        put?: never;
        post: operations["api_budgets_categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets/{budget_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_budgets_check_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets/{budget_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_budgets_close_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets/{budget_id}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_budgets_expenses_list"];
        put?: never;
        post: operations["api_budgets_expenses_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets/{budget_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_budgets_status_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["api_categories_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_categories_partial_update"];
        trace?: never;
    };
    "/api/expenses/{expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_expenses_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["api_expenses_partial_update"];
        trace?: never;
    };
    "/api/expenses/{expense_id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_expenses_void_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Budget: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            /** Format: decimal */
            total_amount: string;
            /** Format: decimal */
            readonly spent_amount: string;
            /** Format: decimal */
            readonly remaining: string;
            currency: string;
            period?: components["schemas"]["PeriodEnum"];
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string | null;
            readonly status: components["schemas"]["BudgetStatusEnum"];
            allow_overspend?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        BudgetCreateRequest: {
            name: string;
            /** Format: decimal */
            total_amount: string;
            currency: string;
            /** @default MONTHLY */
            period: components["schemas"]["PeriodEnum"];
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string | null;
            /** @default false */
            allow_overspend: boolean;
        };
        BudgetStatus: {
            /** Format: decimal */
            totalBudget: string;
            /** Format: decimal */
            spent: string;
            /** Format: decimal */
            remaining: string;
            currency: string;
            perCategory: components["schemas"]["PerCategoryStatus"][];
        };
        /**
         * @description * `ACTIVE` - Active
         *     * `CLOSED` - Closed
         * @enum {string}
         */
        BudgetStatusEnum: "ACTIVE" | "CLOSED";
        Category: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly budget: string;
            name: string;
            /** Format: decimal */
            allocated_amount?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        CategoryCreateRequest: {
            name: string;
            /**
             * Format: decimal
             * @default 0.00
             */
            allocated_amount: string;
        };
        CheckRequest: {
            /** Format: decimal */
            amount: string;
            currency?: string;
            /** Format: uuid */
            category_id?: string | null;
        };
        CheckResult: {
            approved: boolean;
            /** Format: decimal */
            spent: string;
            /** Format: decimal */
            remaining: string;
            wouldOverspend: boolean;
            reason: string | null;
        };
        EmailTokenObtainPairRequest: {
            email: string;
            password: string;
        };
        Expense: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly budget: string;
            /** Format: uuid */
            readonly category: string | null;
            readonly category_name: string | null;
            readonly description: string;
            /** Format: decimal */
            readonly amount: string;
            readonly currency: string;
            /** Format: date */
            readonly date: string;
            readonly status: components["schemas"]["ExpenseStatusEnum"];
            readonly overspent: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ExpenseCreateRequest: {
            /** @default  */
            description: string;
            /** Format: decimal */
            amount: string;
            currency?: string;
            /** Format: date */
            date: string;
            /** Format: uuid */
            category_id?: string | null;
        };
        /**
         * @description * `RECORDED` - Recorded
         *     * `VOIDED` - Voided
         * @enum {string}
         */
        ExpenseStatusEnum: "RECORDED" | "VOIDED";
        PaginatedBudgetList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Budget"][];
        };
        PaginatedExpenseList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Expense"][];
        };
        PatchedBudgetUpdateRequest: {
            name?: string;
            /** Format: decimal */
            total_amount?: string;
            allow_overspend?: boolean;
            period?: components["schemas"]["PeriodEnum"];
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string | null;
        };
        PatchedCategoryUpdateRequest: {
            name?: string;
            /** Format: decimal */
            allocated_amount?: string;
        };
        PatchedExpenseUpdateRequest: {
            description?: string;
            /** Format: decimal */
            amount?: string;
            /** Format: date */
            date?: string;
            /** Format: uuid */
            category_id?: string | null;
        };
        PerCategoryStatus: {
            category: string;
            categoryId: string;
            /** Format: decimal */
            allocated: string;
            /** Format: decimal */
            spent: string;
            /** Format: decimal */
            remaining: string;
        };
        /**
         * @description * `ONE_TIME` - One time
         *     * `WEEKLY` - Weekly
         *     * `MONTHLY` - Monthly
         *     * `YEARLY` - Yearly
         * @enum {string}
         */
        PeriodEnum: "ONE_TIME" | "WEEKLY" | "MONTHLY" | "YEARLY";
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        TokenRefresh: {
            readonly access: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        User: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly role: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailTokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmailTokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["EmailTokenObtainPairRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    api_auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    api_auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    api_budgets_list: {
        parameters: {
            query?: {
                currency?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                pageSize?: number;
                /**
                 * @description * `ONE_TIME` - One time
                 *     * `WEEKLY` - Weekly
                 *     * `MONTHLY` - Monthly
                 *     * `YEARLY` - Yearly
                 */
                period?: "MONTHLY" | "ONE_TIME" | "WEEKLY" | "YEARLY";
                /**
                 * @description * `ACTIVE` - Active
                 *     * `CLOSED` - Closed
                 */
                status?: "ACTIVE" | "CLOSED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBudgetList"];
                };
            };
        };
    };
    api_budgets_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BudgetCreateRequest"];
                "multipart/form-data": components["schemas"]["BudgetCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Budget"];
                };
            };
        };
    };
    api_budgets_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Budget"];
                };
            };
        };
    };
    api_budgets_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Budget soft-deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_budgets_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBudgetUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBudgetUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedBudgetUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Budget"];
                };
            };
        };
    };
    api_budgets_categories_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    api_budgets_categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CategoryCreateRequest"];
                "multipart/form-data": components["schemas"]["CategoryCreateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    api_budgets_check_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CheckRequest"];
                "multipart/form-data": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResult"];
                };
            };
        };
    };
    api_budgets_close_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Budget"];
                };
            };
        };
    };
    api_budgets_expenses_list: {
        parameters: {
            query?: {
                category?: string;
                date_from?: string;
                date_to?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                pageSize?: number;
                /**
                 * @description * `RECORDED` - Recorded
                 *     * `VOIDED` - Voided
                 */
                status?: "RECORDED" | "VOIDED";
            };
            header?: never;
            path: {
                budget_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedExpenseList"];
                };
            };
        };
    };
    api_budgets_expenses_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ExpenseCreateRequest"];
                "multipart/form-data": components["schemas"]["ExpenseCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
        };
    };
    api_budgets_status_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetStatus"];
                };
            };
        };
    };
    api_categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCategoryUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCategoryUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedCategoryUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    api_expenses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
        };
    };
    api_expenses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedExpenseUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedExpenseUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedExpenseUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
        };
    };
    api_expenses_void_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
        };
    };
}
