// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TripWeaver.Infrastructure.Persistence;

#nullable disable

namespace TripWeaver.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617145825_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TripWeaver.Features.Itineraries.Itinerary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BudgetRemaining")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("BudgetTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character(6)")
                        .IsFixedLength();

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WithinBudget")
                        .HasColumnType("boolean");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("itineraries", (string)null);
                });

            modelBuilder.Entity("TripWeaver.Features.Itineraries.ItineraryActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("EstimatedCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("ItineraryDayId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryDayId");

                    b.ToTable("itinerary_activities", (string)null);
                });

            modelBuilder.Entity("TripWeaver.Features.Itineraries.ItineraryDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<decimal?>("HighC")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("ItineraryId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("LowC")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId", "Date");

                    b.ToTable("itinerary_days", (string)null);
                });

            modelBuilder.Entity("TripWeaver.Features.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TripWeaver.Features.Itineraries.Itinerary", b =>
                {
                    b.HasOne("TripWeaver.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TripWeaver.Features.Itineraries.Snapshots.BudgetSummary", "Budget", b1 =>
                        {
                            b1.Property<Guid>("ItineraryId");

                            b1.Property<string>("Currency")
                                .IsRequired();

                            b1.Property<decimal>("Remaining")
                                .HasPrecision(12, 2);

                            b1.Property<decimal>("Spent")
                                .HasPrecision(12, 2);

                            b1.Property<decimal>("TotalBudget")
                                .HasPrecision(12, 2);

                            b1.HasKey("ItineraryId");

                            b1.ToTable("itineraries");

                            b1
                                .ToJson("budget")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ItineraryId");
                        });

                    b.OwnsOne("TripWeaver.Features.Itineraries.Snapshots.FlightSelection", "Flight", b1 =>
                        {
                            b1.Property<Guid>("ItineraryId");

                            b1.Property<string>("Airline")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("ArrivalTime");

                            b1.Property<string>("Currency")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("DepartureTime");

                            b1.Property<string>("Destination")
                                .IsRequired();

                            b1.Property<string>("FlightId")
                                .IsRequired();

                            b1.Property<string>("Origin")
                                .IsRequired();

                            b1.Property<decimal>("Price")
                                .HasPrecision(12, 2);

                            b1.Property<int>("Stops");

                            b1.HasKey("ItineraryId");

                            b1.ToTable("itineraries");

                            b1
                                .ToJson("flight")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ItineraryId");
                        });

                    b.OwnsOne("TripWeaver.Features.Itineraries.Snapshots.HotelSelection", "Hotel", b1 =>
                        {
                            b1.Property<Guid>("ItineraryId");

                            b1.PrimitiveCollection<string>("Amenities")
                                .IsRequired();

                            b1.Property<DateOnly>("CheckIn");

                            b1.Property<DateOnly>("CheckOut");

                            b1.Property<string>("Currency")
                                .IsRequired();

                            b1.Property<string>("HotelId")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<decimal>("PricePerNight")
                                .HasPrecision(12, 2);

                            b1.Property<int>("StarRating");

                            b1.Property<decimal>("TotalPrice")
                                .HasPrecision(12, 2);

                            b1.HasKey("ItineraryId");

                            b1.ToTable("itineraries");

                            b1
                                .ToJson("hotel")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ItineraryId");
                        });

                    b.OwnsOne("TripWeaver.Features.Itineraries.Snapshots.WeatherSnapshot", "Weather", b1 =>
                        {
                            b1.Property<Guid>("ItineraryId");

                            b1.HasKey("ItineraryId");

                            b1.ToTable("itineraries");

                            b1
                                .ToJson("weather")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ItineraryId");

                            b1.OwnsMany("TripWeaver.Features.Itineraries.Snapshots.DailyForecastSnapshot", "Forecast", b2 =>
                                {
                                    b2.Property<Guid>("WeatherSnapshotItineraryId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Condition")
                                        .IsRequired();

                                    b2.Property<DateOnly>("Date");

                                    b2.Property<decimal>("High")
                                        .HasPrecision(12, 2);

                                    b2.Property<decimal>("Low")
                                        .HasPrecision(12, 2);

                                    b2.HasKey("WeatherSnapshotItineraryId", "__synthesizedOrdinal");

                                    b2.ToTable("itineraries");

                                    b2.WithOwner()
                                        .HasForeignKey("WeatherSnapshotItineraryId");
                                });

                            b1.Navigation("Forecast");
                        });

                    b.Navigation("Budget")
                        .IsRequired();

                    b.Navigation("Flight")
                        .IsRequired();

                    b.Navigation("Hotel")
                        .IsRequired();

                    b.Navigation("Weather")
                        .IsRequired();
                });

            modelBuilder.Entity("TripWeaver.Features.Itineraries.ItineraryActivity", b =>
                {
                    b.HasOne("TripWeaver.Features.Itineraries.ItineraryDay", null)
                        .WithMany("Activities")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripWeaver.Features.Itineraries.ItineraryDay", b =>
                {
                    b.HasOne("TripWeaver.Features.Itineraries.Itinerary", null)
                        .WithMany("Days")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripWeaver.Features.Itineraries.Itinerary", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("TripWeaver.Features.Itineraries.ItineraryDay", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
