/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/room-types/{id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["upsertAvailability"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hotels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hotels/{id}/room-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRoomType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hotels/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{reference}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/room-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
    "/api/hotels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/hotels/{id}/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["rooms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AvailabilityUpsertRequest: {
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** Format: int32 */
            totalRooms: number;
            /** Format: int32 */
            availableRooms?: number;
            priceOverride?: number;
        };
        ApiEnvelopeListAvailabilityNightDto: {
            data?: components["schemas"]["AvailabilityNightDto"][];
        };
        AvailabilityNightDto: {
            /** Format: date */
            date?: string;
            /** Format: int32 */
            totalRooms?: number;
            /** Format: int32 */
            availableRooms?: number;
            priceOverride?: number;
        };
        CreateHotelRequest: {
            name: string;
            description?: string;
            city: string;
            country: string;
            address?: string;
            /** Format: int32 */
            starRating: number;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            timezone: string;
            amenities?: string[];
        };
        ApiEnvelopeHotelDto: {
            data?: components["schemas"]["HotelDto"];
        };
        HotelDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string;
            city?: string;
            country?: string;
            address?: string;
            /** Format: int32 */
            starRating?: number;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            timezone?: string;
            amenities?: string[];
        };
        CreateRoomTypeRequest: {
            name: string;
            description?: string;
            /** Format: int32 */
            capacity: number;
            basePricePerNight: number;
            currency: string;
            amenities?: string[];
        };
        ApiEnvelopeRoomTypeDto: {
            data?: components["schemas"]["RoomTypeDto"];
        };
        RoomTypeDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string;
            /** Format: int32 */
            capacity?: number;
            basePricePerNight?: number;
            currency?: string;
            amenities?: string[];
        };
        HotelSearchRequest: {
            city: string;
            country?: string;
            /** Format: date */
            checkInDate: string;
            /** Format: date */
            checkOutDate: string;
            /** Format: int32 */
            guests: number;
            /** Format: int32 */
            rooms?: number;
            /** Format: int32 */
            starRating?: number;
            priceMin?: number;
            priceMax?: number;
            amenities?: string[];
            sortBy?: string;
            order?: string;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        HotelSearchItem: {
            /** Format: uuid */
            hotelId?: string;
            name?: string;
            description?: string;
            city?: string;
            country?: string;
            /** Format: int32 */
            starRating?: number;
            timezone?: string;
            amenities?: string[];
            currency?: string;
            pricePerNight?: number;
            totalPrice?: number;
            roomTypes?: components["schemas"]["RoomTypeOffer"][];
        };
        ListEnvelopeHotelSearchItem: {
            data?: components["schemas"]["HotelSearchItem"][];
            meta?: components["schemas"]["PageMeta"];
        };
        PageMeta: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int64 */
            total?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        RoomTypeOffer: {
            /** Format: uuid */
            roomTypeId?: string;
            name?: string;
            description?: string;
            /** Format: int32 */
            capacity?: number;
            currency?: string;
            pricePerNight?: number;
            totalPrice?: number;
            /** Format: int32 */
            availableRooms?: number;
            amenities?: string[];
        };
        CreateBookingRequest: {
            /** Format: uuid */
            roomTypeId: string;
            /** Format: date */
            checkInDate: string;
            /** Format: date */
            checkOutDate: string;
            /** Format: int32 */
            numberOfRooms: number;
            guests: components["schemas"]["GuestRequest"][];
            contactEmail: string;
            currency?: string;
        };
        GuestRequest: {
            firstName: string;
            lastName: string;
            /** Format: date */
            dateOfBirth?: string;
        };
        ApiEnvelopeBookingDto: {
            data?: components["schemas"]["BookingDto"];
        };
        BookingDto: {
            /** Format: uuid */
            id?: string;
            reference?: string;
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            hotelId?: string;
            /** Format: uuid */
            roomTypeId?: string;
            /** Format: date */
            checkInDate?: string;
            /** Format: date */
            checkOutDate?: string;
            /** Format: int32 */
            numberOfRooms?: number;
            /** Format: int32 */
            numberOfGuests?: number;
            /** @enum {string} */
            status?: "PENDING" | "CONFIRMED" | "CANCELLED";
            totalPrice?: number;
            currency?: string;
            contactEmail?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            cancelledAt?: string;
            guests?: components["schemas"]["GuestDto"][];
        };
        GuestDto: {
            /** Format: uuid */
            id?: string;
            firstName?: string;
            lastName?: string;
            /** Format: date */
            dateOfBirth?: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
        };
        ApiEnvelopeAuthResponse: {
            data?: components["schemas"]["AuthResponse"];
        };
        AuthResponse: {
            token?: string;
            user?: components["schemas"]["UserDto"];
        };
        UserDto: {
            /** Format: uuid */
            id?: string;
            email?: string;
            /** @enum {string} */
            role?: "USER" | "ADMIN";
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        UpdateRoomTypeRequest: {
            name?: string;
            description?: string;
            /** Format: int32 */
            capacity?: number;
            basePricePerNight?: number;
            currency?: string;
            amenities?: string[];
        };
        UpdateHotelRequest: {
            name?: string;
            description?: string;
            city?: string;
            country?: string;
            address?: string;
            /** Format: int32 */
            starRating?: number;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            timezone?: string;
            amenities?: string[];
        };
        ApiEnvelopeHotelDetailDto: {
            data?: components["schemas"]["HotelDetailDto"];
        };
        HotelDetailDto: {
            hotel?: components["schemas"]["HotelDto"];
            roomTypes?: components["schemas"]["RoomTypeDto"][];
            availability?: components["schemas"]["RoomTypeOffer"][];
        };
        ApiEnvelopeListRoomTypeOffer: {
            data?: components["schemas"]["RoomTypeOffer"][];
        };
        ListEnvelopeBookingDto: {
            data?: components["schemas"]["BookingDto"][];
            meta?: components["schemas"]["PageMeta"];
        };
        ApiEnvelopeUserDto: {
            data?: components["schemas"]["UserDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upsertAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityUpsertRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeListAvailabilityNightDto"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHotelRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeHotelDto"];
                };
            };
        };
    };
    createRoomType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomTypeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeRoomTypeDto"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HotelSearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ListEnvelopeHotelSearchItem"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ListEnvelopeBookingDto"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeBookingDto"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeBookingDto"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeAuthResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeAuthResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoomTypeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeRoomTypeDto"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: {
                checkInDate?: string;
                checkOutDate?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeHotelDetailDto"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateHotelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeHotelDto"];
                };
            };
        };
    };
    rooms: {
        parameters: {
            query: {
                checkInDate: string;
                checkOutDate: string;
                guests?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeListRoomTypeOffer"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeBookingDto"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiEnvelopeUserDto"];
                };
            };
        };
    };
}
