// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: current.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentWeather = `-- name: GetCurrentWeather :one
SELECT location_id, temp_c, condition, humidity, wind_kph, observed_at FROM current_weather WHERE location_id = $1
`

func (q *Queries) GetCurrentWeather(ctx context.Context, locationID uuid.UUID) (CurrentWeather, error) {
	row := q.db.QueryRow(ctx, getCurrentWeather, locationID)
	var i CurrentWeather
	err := row.Scan(
		&i.LocationID,
		&i.TempC,
		&i.Condition,
		&i.Humidity,
		&i.WindKph,
		&i.ObservedAt,
	)
	return i, err
}

const upsertCurrentWeather = `-- name: UpsertCurrentWeather :one
INSERT INTO current_weather (location_id, temp_c, condition, humidity, wind_kph, observed_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (location_id) DO UPDATE SET
  temp_c      = EXCLUDED.temp_c,
  condition   = EXCLUDED.condition,
  humidity    = EXCLUDED.humidity,
  wind_kph    = EXCLUDED.wind_kph,
  observed_at = now()
RETURNING location_id, temp_c, condition, humidity, wind_kph, observed_at
`

type UpsertCurrentWeatherParams struct {
	LocationID uuid.UUID
	TempC      float64
	Condition  Condition
	Humidity   pgtype.Int4
	WindKph    pgtype.Float8
}

func (q *Queries) UpsertCurrentWeather(ctx context.Context, arg UpsertCurrentWeatherParams) (CurrentWeather, error) {
	row := q.db.QueryRow(ctx, upsertCurrentWeather,
		arg.LocationID,
		arg.TempC,
		arg.Condition,
		arg.Humidity,
		arg.WindKph,
	)
	var i CurrentWeather
	err := row.Scan(
		&i.LocationID,
		&i.TempC,
		&i.Condition,
		&i.Humidity,
		&i.WindKph,
		&i.ObservedAt,
	)
	return i, err
}
