// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forecasts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const dailyRange = `-- name: DailyRange :many
SELECT id, location_id, date, high_c, low_c, condition, precipitation_chance, humidity, wind_kph, created_at, updated_at FROM daily_forecasts
WHERE location_id = $1 AND date BETWEEN $2 AND $3
ORDER BY date ASC
`

type DailyRangeParams struct {
	LocationID uuid.UUID
	Date       pgtype.Date
	Date_2     pgtype.Date
}

func (q *Queries) DailyRange(ctx context.Context, arg DailyRangeParams) ([]DailyForecast, error) {
	rows, err := q.db.Query(ctx, dailyRange, arg.LocationID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyForecast{}
	for rows.Next() {
		var i DailyForecast
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Date,
			&i.HighC,
			&i.LowC,
			&i.Condition,
			&i.PrecipitationChance,
			&i.Humidity,
			&i.WindKph,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyForecast = `-- name: UpsertDailyForecast :one
INSERT INTO daily_forecasts (
  location_id, date, high_c, low_c, condition, precipitation_chance, humidity, wind_kph
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (location_id, date) DO UPDATE SET
  high_c               = EXCLUDED.high_c,
  low_c                = EXCLUDED.low_c,
  condition            = EXCLUDED.condition,
  precipitation_chance = EXCLUDED.precipitation_chance,
  humidity             = EXCLUDED.humidity,
  wind_kph             = EXCLUDED.wind_kph,
  updated_at           = now()
RETURNING id, location_id, date, high_c, low_c, condition, precipitation_chance, humidity, wind_kph, created_at, updated_at
`

type UpsertDailyForecastParams struct {
	LocationID          uuid.UUID
	Date                pgtype.Date
	HighC               float64
	LowC                float64
	Condition           Condition
	PrecipitationChance pgtype.Int4
	Humidity            pgtype.Int4
	WindKph             pgtype.Float8
}

func (q *Queries) UpsertDailyForecast(ctx context.Context, arg UpsertDailyForecastParams) (DailyForecast, error) {
	row := q.db.QueryRow(ctx, upsertDailyForecast,
		arg.LocationID,
		arg.Date,
		arg.HighC,
		arg.LowC,
		arg.Condition,
		arg.PrecipitationChance,
		arg.Humidity,
		arg.WindKph,
	)
	var i DailyForecast
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Date,
		&i.HighC,
		&i.LowC,
		&i.Condition,
		&i.PrecipitationChance,
		&i.Humidity,
		&i.WindKph,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
