// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLocations = `-- name: CountLocations :one
SELECT count(*) FROM locations
WHERE ($1::text IS NULL
       OR name ILIKE '%' || $1 || '%'
       OR city ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR country = $2)
`

type CountLocationsParams struct {
	Q       pgtype.Text
	Country pgtype.Text
}

func (q *Queries) CountLocations(ctx context.Context, arg CountLocationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLocations, arg.Q, arg.Country)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLocation = `-- name: DeleteLocation :execrows
DELETE FROM locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLocation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findLocationsByCity = `-- name: FindLocationsByCity :many
SELECT id, name, city, country, latitude, longitude, timezone, created_at, updated_at FROM locations
WHERE lower(city) = lower($1)
  AND ($2::text IS NULL OR country = $2)
ORDER BY country ASC
`

type FindLocationsByCityParams struct {
	City    string
	Country pgtype.Text
}

func (q *Queries) FindLocationsByCity(ctx context.Context, arg FindLocationsByCityParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, findLocationsByCity, arg.City, arg.Country)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, name, city, country, latitude, longitude, timezone, created_at, updated_at FROM locations WHERE id = $1
`

func (q *Queries) GetLocationByID(ctx context.Context, id uuid.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLocation = `-- name: InsertLocation :one
INSERT INTO locations (name, city, country, latitude, longitude, timezone)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, city, country, latitude, longitude, timezone, created_at, updated_at
`

type InsertLocationParams struct {
	Name      string
	City      string
	Country   string
	Latitude  float64
	Longitude float64
	Timezone  string
}

func (q *Queries) InsertLocation(ctx context.Context, arg InsertLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, insertLocation,
		arg.Name,
		arg.City,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
		arg.Timezone,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchLocations = `-- name: SearchLocations :many
SELECT id, name, city, country, latitude, longitude, timezone, created_at, updated_at FROM locations
WHERE ($1::text IS NULL
       OR name ILIKE '%' || $1 || '%'
       OR city ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR country = $2)
ORDER BY city ASC, name ASC
LIMIT $4 OFFSET $3
`

type SearchLocationsParams struct {
	Q       pgtype.Text
	Country pgtype.Text
	Offset  int32
	Limit   int32
}

func (q *Queries) SearchLocations(ctx context.Context, arg SearchLocationsParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, searchLocations,
		arg.Q,
		arg.Country,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations SET
  name      = COALESCE($1, name),
  city      = COALESCE($2, city),
  country   = COALESCE($3, country),
  latitude  = COALESCE($4, latitude),
  longitude = COALESCE($5, longitude),
  timezone  = COALESCE($6, timezone),
  updated_at = now()
WHERE id = $7
RETURNING id, name, city, country, latitude, longitude, timezone, created_at, updated_at
`

type UpdateLocationParams struct {
	Name      pgtype.Text
	City      pgtype.Text
	Country   pgtype.Text
	Latitude  pgtype.Float8
	Longitude pgtype.Float8
	Timezone  pgtype.Text
	ID        uuid.UUID
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.Name,
		arg.City,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
		arg.Timezone,
		arg.ID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
