// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountLocations(ctx context.Context, arg CountLocationsParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	DailyRange(ctx context.Context, arg DailyRangeParams) ([]DailyForecast, error)
	DeleteLocation(ctx context.Context, id uuid.UUID) (int64, error)
	FindLocationsByCity(ctx context.Context, arg FindLocationsByCityParams) ([]Location, error)
	GetCurrentWeather(ctx context.Context, locationID uuid.UUID) (CurrentWeather, error)
	GetLocationByID(ctx context.Context, id uuid.UUID) (Location, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	InsertLocation(ctx context.Context, arg InsertLocationParams) (Location, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	SearchLocations(ctx context.Context, arg SearchLocationsParams) ([]Location, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpsertCurrentWeather(ctx context.Context, arg UpsertCurrentWeatherParams) (CurrentWeather, error)
	UpsertDailyForecast(ctx context.Context, arg UpsertDailyForecastParams) (DailyForecast, error)
}

var _ Querier = (*Queries)(nil)
